spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: yqs
logging:
  level:
    root: warn
    com.yqs: info
  file:
    name: src/log/blog-pro.log
server:
  port: 8081